name: docker
on: 
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - 
        name: checkout
        uses: actions/checkout@v2
      -
        name: build and test
        run: |
          docker build -t worker:testing --no-cache worker/
          docker network create worker
          docker run -d --network worker --name redis-svc redis
          docker run --network worker worker:testing
          while true
            do
              sleep 1
              docker ps | grep Up && break
            done
          while true
            do
              sleep 1
              docker ps | grep python && break
            done
