name: docker
on: 
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - 
        name: checkout
        uses: actions/checkout@v2
      -
        name: worker
        run: |
          set -x
          docker build -t worker:testing --no-cache worker/
          docker network create worker
          docker run -d --network worker --name redis-svc redis
          docker run -d --network worker --name worker worker:testing
          while true
            do
              sleep 10
              docker exec worker ps | grep python && break
            done
